import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nextjs crash course',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ `${inter.className} container mx-auto`}>
        <nav className="flex justify-between items-center">
          <a href="/" >LOGO</a>
          <ul className='flex space-x-4'>
            <li>
              
              <Link href="/about">About</Link>
            </li>
            <li>
              
            <Link href="/contact">Contact</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
